author = 'Frank Grossgasteiger'
baseURL = 'https://grossgasteiger.de'
description = 'Geschichte und Aktuelles'
name = 'Familie Großgasteiger'
theme = '2018'
title = 'Familie Großgasteiger'
url = 'https://grossgasteiger.de'
