name = "2018"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://www.grossgasteiger.de"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Frank Großgasteiger"
  homepage = "https://www.grossgasteiger.de"

